### ISSUE TITLE
Undefined method `dig' for #<Hash:>

### ISSUE THREAD

**Issue by rkrayovskyy** [hyperoslo/facebook-messenger#95]
Hi,

the following error raises every time I am sending a message:

> NoMethodError (undefined method `dig' for #<Hash:0x007fa04e5762a0>):
>   
> facebook-messenger (0.11.0) lib/facebook/messenger/server.rb:98:in `generate_hmac'

Gem version 0.11.0
Rails 5.0.0.1
Ruby 2.2.4

**Comment by enderahmetyurt** [comment]
You should check your Ruby version. It should be 2.3

**Comment by frodsan** [comment]
Is the minimum version is 2.3, then that should be specified in the gemspec:

```
s.required_ruby_version = ">= 2.3.0"
```

**Comment by rkrayovskyy** [comment]
correct, it works with Ruby 2.3.x and higher since Hash#dig has been introduced since 2.3.0

worth adding dependency or specifying in documentation...

**Comment by jgorset** [comment]
Thanks for catching this, @rkrayovskyy. It's not intended that Ruby 2.3.0 be the minimum version for this gem. I [refactored it](https://github.com/hyperoslo/facebook-messenger/commit/4fc35e082f1619c23e0fd3e23b42f131f61d61cd) and [released v0.11.1](https://github.com/hyperoslo/facebook-messenger/commit/e9f403fda82d17df05fa2f0e0bb15dada5539c4f).
