### ISSUE TITLE
Rails 5 undefined method `on'

### ISSUE THREAD

**Issue by FlintOFF** [hyperoslo/facebook-messenger#56]
Hi.
I migrated my project from RAILS 4.2.6 to RAILS 5.0.0.
I see an error when I try start server on RAILS 5.0.0, work well on RAILS 4.2.6.
Error:

```
<top (required)>: undefined method 'on' for Bot:Module (NoMethodError)
from /home/vitalii/.rvm/gems/ruby-2.3.1@cai_bot/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in 'require'
```

Code:
```
include Facebook::Messenger
Bot.on :optin do |optin|
  recipient(optin)

  Bot.deliver(
      recipient: optin.sender,
      message: {
          text: 'Welcome message'
      }
  )
end 
```

**Comment by FlintOFF** [comment]
My fault.
I created a new project called BOT.
I changed the name of project and the error has disappeared
